CRYSTAL_BIN ?= `which crystal`
SAM_PATH ?= "sam.cr"
SHARDS_BIN ?= `which shards`

# === Sam shortcut
# next lines are autogenerated and any changes will be discarded after regenerating
.PHONY: sam
sam:
	$(CRYSTAL_BIN) $(SAM_PATH) $(filter-out $@,$(MAKECMDGOALS))
%:
	@:
# === Sam shortcut

server:
	$(CRYSTAL_BIN) run src/api.cr

install:
	$(SHARDS_BIN) install